### ISSUE TITLE
no upload possible??

### ISSUE THREAD

**Issue by krikk** [rzander/ruckzuck#85]
new to ruckzuck, tried to fix a problem in one of your packages, but i can not upload the new package, upload button is greyed out??

i updated the irfanview package...

[EXP_IrfanView (remove only)4.54X64.zip](https://github.com/rzander/ruckzuck/files/4294949/EXP_IrfanView.remove.only.4.54X64.zip)

**Comment by rzander** [comment]
To unlock the upload button, you have to edit the download URL. 
If the Version of the Product does not change (as in this case), it's the best to post the requested changes here on github... So you did everything right.

I've fixed the Uninstall string and added the "/allusers=1" install parameter

**Comment by krikk** [comment]
you missed my other parameter:

` /ini="%APPDATA%\IrfanView"`

this is important, otherwise the user is not able to save settings, because the .ini file is in the programfiles directory...

**Comment by rzander** [comment]
fixed; I had some concerns as %APPDATA% is not a PowerShell variable but it seems to work...
